FROM quay.io/jupyter/pytorch-notebook:cuda12-python-3.11.8

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    nvidia-cuda-toolkit

RUN python3 -m pip install --no-cache-dir \
    jupyterlab-language-pack-zh-TW
