# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Build Docker Image Dockerfile.pytorch-cuda12

on:
  push:
    paths:
      - '**/Dockerfile.pytorch-cuda12'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE: prinsss/ga-hit-counter

jobs:
  build_docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Create Docker Image in Github
      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build And Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.pytorch-cuda12
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART }}/${{ env.GITHUB_REPOSITORY_NAME_PART }}:pytorch-cuda12-${{ env.GITHUB_REF_NAME }}
            ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART }}/${{ env.GITHUB_REPOSITORY_NAME_PART }}:pytorch-cuda12-latest
